// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8iKS-Fa9Yqxbg6Uyfb9gH29a3SHMODio',
    appId: '1:1065595138950:web:2ce4424d064e1c2d7cf207',
    messagingSenderId: '1065595138950',
    projectId: 'ecs198f-project',
    authDomain: 'ecs198f-project.firebaseapp.com',
    storageBucket: 'ecs198f-project.appspot.com',
    measurementId: 'G-KR2YLJWKVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8H1h2PKdVkoaxtnwwMVemiuVJ7T4Hxg',
    appId: '1:1065595138950:android:2f1d89a605e22ee37cf207',
    messagingSenderId: '1065595138950',
    projectId: 'ecs198f-project',
    storageBucket: 'ecs198f-project.appspot.com',
  );
}
